-- Scout da Pelada - resultados entre times
-- Execute UMA VEZ no SQL Editor do Supabase.

begin;

create table if not exists public.jogos (
  id bigint generated by default as identity primary key,
  rodada_id bigint not null references public.rodadas(id) on delete cascade,
  time_a text not null,
  time_b text not null,
  resultado text not null check (resultado in ('A','E','B')),
  criado_em timestamptz not null default now(),
  check (time_a <> time_b)
);

alter table public.jogos enable row level security;
grant select on public.jogos to anon, authenticated;
grant insert, update, delete on public.jogos to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "publico_le_jogos" on public.jogos;
create policy "publico_le_jogos" on public.jogos for select to anon using (true);

drop policy if exists "autenticado_le_jogos" on public.jogos;
create policy "autenticado_le_jogos" on public.jogos for select to authenticated using (true);

drop policy if exists "somente_admin_insere_jogos" on public.jogos;
create policy "somente_admin_insere_jogos" on public.jogos for insert to authenticated with check (public.is_app_admin());

drop policy if exists "somente_admin_edita_jogos" on public.jogos;
create policy "somente_admin_edita_jogos" on public.jogos for update to authenticated using (public.is_app_admin()) with check (public.is_app_admin());

drop policy if exists "somente_admin_exclui_jogos" on public.jogos;
create policy "somente_admin_exclui_jogos" on public.jogos for delete to authenticated using (public.is_app_admin());

commit;

select 'ok' as resultados_times_configurados;
