-- Scout da Pelada - scouts por partida + saldo de gols
-- Execute UMA VEZ no SQL Editor do Supabase.

begin;

create table if not exists public.jogo_scouts (
  id bigint generated by default as identity primary key,
  jogo_id bigint not null references public.jogos(id) on delete cascade,
  jogador_id bigint not null references public.jogadores(id) on delete cascade,
  gols integer not null default 0 check (gols >= 0),
  assistencias integer not null default 0 check (assistencias >= 0),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (jogo_id, jogador_id)
);

alter table public.jogo_scouts enable row level security;
grant select on public.jogo_scouts to anon, authenticated;
grant insert, update, delete on public.jogo_scouts to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "publico_le_jogo_scouts" on public.jogo_scouts;
create policy "publico_le_jogo_scouts" on public.jogo_scouts for select to anon using (true);
drop policy if exists "autenticado_le_jogo_scouts" on public.jogo_scouts;
create policy "autenticado_le_jogo_scouts" on public.jogo_scouts for select to authenticated using (true);
drop policy if exists "somente_admin_insere_jogo_scouts" on public.jogo_scouts;
create policy "somente_admin_insere_jogo_scouts" on public.jogo_scouts for insert to authenticated with check (public.is_app_admin());
drop policy if exists "somente_admin_edita_jogo_scouts" on public.jogo_scouts;
create policy "somente_admin_edita_jogo_scouts" on public.jogo_scouts for update to authenticated using (public.is_app_admin()) with check (public.is_app_admin());
drop policy if exists "somente_admin_exclui_jogo_scouts" on public.jogo_scouts;
create policy "somente_admin_exclui_jogo_scouts" on public.jogo_scouts for delete to authenticated using (public.is_app_admin());

create or replace function public.sync_jogo_scout_total() returns trigger language plpgsql security definer set search_path=public as $$
declare v_rodada_id bigint; v_jogador_id bigint; dg integer:=0; da integer:=0;
begin
 if tg_op='DELETE' then select rodada_id into v_rodada_id from public.jogos where id=old.jogo_id; v_jogador_id:=old.jogador_id; dg:=-old.gols; da:=-old.assistencias;
 elsif tg_op='INSERT' then select rodada_id into v_rodada_id from public.jogos where id=new.jogo_id; v_jogador_id:=new.jogador_id; dg:=new.gols; da:=new.assistencias;
 else select rodada_id into v_rodada_id from public.jogos where id=new.jogo_id; v_jogador_id:=new.jogador_id; dg:=new.gols-old.gols; da:=new.assistencias-old.assistencias; end if;
 if v_rodada_id is not null and (dg<>0 or da<>0) then update public.scouts set gols=greatest(0,coalesce(gols,0)+dg), assistencias=greatest(0,coalesce(assistencias,0)+da) where rodada_id=v_rodada_id and jogador_id=v_jogador_id; end if;
 if tg_op='DELETE' then return old; else return new; end if;
end; $$;
drop trigger if exists trg_sync_jogo_scout_total on public.jogo_scouts;
create trigger trg_sync_jogo_scout_total after insert or update or delete on public.jogo_scouts for each row execute function public.sync_jogo_scout_total();
commit;
select 'ok' as scouts_por_partida_configurados;
